defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Heng Li
subtitle: University of Cincinnati Business Analytics Graduate Student

left_side:
  background_image: "./assets/images/left-background.jpg"
  background_color: "#000000"
  close_button_color: "#FFFFFF"
  text_color: "#FFFFFF"
  head_shot: "![head_shot](https://raw.githubusercontent.com/HengLi1029/image/master/pic%20for%20markdown.jpg?token=ANL7NAKFXTW3HNPCH6XNNSS7DD2ZG)"

footer:
  copyright_text: "&copy; Heng Li"

# Side Menu Links
menu:
  - text: About Me
    link: /about_me
    icon: ""

  - text: Research & Projects
    link: /skills-and-offers
    icon: ""

  - text: Skills
    link: /skills-and-offers
    icon: ""

  - text: Business Experience
    link: /Business_Experience
    icon: ""
    
  - text: Contact Me
    link: /contact
    icon: ""



# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/heng-li-leo
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/HengLi1029
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/profile.php?id=100010435814203
    icon: fab fa-facebook-square

  


    
