defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Heng Li
subtitle: University of Cincinnati Business Analytics Graduate Student

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Heng Li"

# Side Menu Links
menu:
  - text: CV
    link: /resume
    icon: ""

  - text: Research & Projects
    link: /skills-and-offers
    icon: ""

  - text: Skills
    link: /skills-and-offers
    icon: ""

  - text: Business Experience
    link: /posts
    icon: ""
    
  - text: Contact Me
    link: /contact
    icon: ""



# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
