defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Heng Li
subtitle: University of Cincinnati Business Analytics Graduate Student

 left_side:
  background_image: "./assets/images/left-background.jpg"
  background_color: "#98FB98"
  close_button_color: "#FFFFFF"
  text_color: "#FFFFFF"
  head_shot: "![head_shot](https://raw.githubusercontent.com/HengLi1029/image/master/pic%20for%20markdown.jpg?token=ANL7NAKFXTW3HNPCH6XNNSS7DD2ZG)"

footer:
  copyright_text: "&copy; Heng Li"

# Side Menu Links
menu:
  - text: About Me
    link: /resume
    icon: ""

  - text: Research & Projects
    link: /skills-and-offers
    icon: ""

  - text: Skills
    link: /skills-and-offers
    icon: ""

  - text: Business Experience
    link: /posts
    icon: ""
    
  - text: Contact Me
    link: /contact
    icon: ""



# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
